name: Gree2MQTT
version: 1.0.0
slug: gree2mqtt
description: Integrate WiFi GREE protocol HVAC devices with HA
url: https://github.com/guntiss/gree2mqtt-ha-addon
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
discovery:
  - mqtt
options:
  debug: "false"
  mqtt:
    broker_url: mqtt://localhost
    username: ""
    password: ""
    retain: "true"
  devices:
    - hvac_host: 192.168.100.123
      mqtt_topic_prefix: home/gree_bedroom
schema:
  debug: bool?
  hvac_host: str?
  mqtt:
    broker_url: str
    topic_prefix: str?
    username: str?
    password: str?
    retain: str?
  devices:
    - hvac_host: str
      mqtt_topic_prefix: str
